task:
  name: FreeBSD

  freebsd_instance:
    image_family: freebsd-13-2

  install_script: pkg install -y crystal shards chafa imagemagick7 libarchive
  build_script: make
  bin_artifacts:
    path: ./bin/crpreview
