task:
  # Basic metadata:
  name: Build executables and pack to artifacts (FreeBSD)

  # The build machine:
  freebsd_instance:
    image_family: freebsd-13-2

  # No environment variables provided.

  # Instructions:
  install_script: pkg install -y crystal shards chafa imagemagick
  build_script: make
  bin_artifacts:
    path: ./bin/crpreview
