task:
  name: Build executables and pack to artifacts (FreeBSD)

  freebsd_instance:
    image_family: freebsd-13-2

  install_script: pkg install -y crystal shards chafa imagemagick7-nox11
  build_script: make
  bin_artifacts:
    path: ./bin/crpreview
