name: MacOS & Ubuntu

on: push

env:
  BINARY_PATH: "./bin/crpreview"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: crystal-lang/install-crystal@v1

      - name: Install Dependencies (MacOS)
        if: startsWith( matrix.os, 'macos')
        run: |
          brew install pkg-config chafa imagemagick libarchive
          brew link --force libarchive

      - name: Install Dependencies (Ubuntu)
        if: startsWith( matrix.os, 'ubuntu')
        run: |
          sudo apt-get install -y libchafa-dev libmagickwand-dev libarchive-dev

      - uses: actions/checkout@v3

      - name: Make build
        run: make

      - name: Set SHA variable
        run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-${{ env.GITHUB_SHA_SHORT }}
          path: ${{ env.BINARY_PATH }}
