on:
  push:
    branches:
    - master

jobs:
  build-:
    name: Install Crystal
    runs-on: ubuntu-latest
    steps:
    - uses: crystal-lang/install-crystal@v1.8.0
    - uses: actions/checkout@v3
    - name: build executable
      run: make
