on:
  push:
    branches:
    - master

jobs:
  build:
    name: Install Crystal
    runs-on: ubuntu-latest
    steps:
    - uses: crystal-lang/install-crystal@v1.8.0
    - name: Build
      run: make
