name: MacOS & Ubuntu

on: push

env:
  BINARY_PATH: "./bin/crpreview"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: crystal-lang/install-crystal@v1
      - uses: actions/checkout@v3

      - name: Install Dependencies & Build (MacOS)
        if: startsWith( matrix.os, 'macos')
        run: |
          brew install pkg-config chafa imagemagick libarchive
          PKG_CONFIG_PATH="/usr/local/opt/libarchive/lib/pkgconfig" make

      - name: Install Dependencies & Build (Ubuntu)
        if: startsWith( matrix.os, 'ubuntu')
        run: |
          sudo apt-get install -y libchafa-dev libmagickwand-dev libarchive-dev
          make

      - name: Set SHA variable
        run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-${{ env.GITHUB_SHA_SHORT }}
          path: ${{ env.BINARY_PATH }}
