on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build excecutable

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: crystal-lang/install-crystal@v1.8.0

      - name: Install Dependencies on MacOS
        if: matrix.os == 'macos-latest'
        run: |
          brew install chafa

      - name: Install Dependencies on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get install libchafa-dev

      - uses: actions/checkout@v3

      - name: Make build
        run: make
