name: MacOS & Ubuntu

on: push

env:
  BINARY_PATH: "./bin/crpreview"

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Download source
        uses: actions/checkout@v4

      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1

      - name: Install Dependencies & Build
        run: |
          brew install pkg-config libarchive
          PKG_CONFIG_PATH=/usr/local/opt/libarchive/lib/pkgconfig:$PKG_CONFIG_PATH make

      - name: Set SHA variable
        run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: macos-latest-${{ env.GITHUB_SHA_SHORT }}
          path: ${{ env.BINARY_PATH }}
